version: '3.8'

services:
  backend:
    build:
      context: ./
    env_file:
      - .env
    ports:
      - "8080:8080"
    depends_on:
      - postgres

  postgres:
    #container_name: gestao_vagas_postgres
    image: postgres
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:

