networks:
  gv-network:
    driver: bridge

services:
  backend:
    build:
      context: ./
    env_file:
      - .env
    ports:
      - "8080:8080"
    networks:
      - gv-network
    depends_on:
      - postgres

  postgres:
    #container_name: gestao_vagas_postgres
    image: postgres
    env_file:
      - .env
    ports:
      - "5432:5432"
    networks:
      - gv-network
    volumes:
      - postgres_data:/var/lib/postgresql/data

  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    volumes:
      - ./config/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    networks:
      - gv-network
    depends_on:
      - backend

  grafana:
     image: grafana/grafana:latest
     ports:
       - 3000:3000
     networks:
       - gv-network

volumes:
  postgres_data:
  prometheus_data:
  grafana_data:

